import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDF = ({ device, id, serialNo, method, status, date, addedAt }) => {
  const doc = new jsPDF();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(37, 99, 235); // secure-blue
  doc.text("SecureWipe  - Wipe Certificate", 20, 20);

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text("Generated by SecureWipe ", 20, 30);

  autoTable(doc, {
    startY: 40,
    head: [["Field", "Value"]],
    body: [
      ["Device", device],
      ["ID", id],
      ["Serial Number", serialNo],
      ["Wipe Method", method || "N/A"],
      ["Status", status],
      ["Wipe Date", new Date(date).toLocaleString()],
      ["Added Date", new Date(addedAt).toLocaleString()],
    ],
    theme: "grid",
    headStyles: { fillColor: [37, 99, 235] },
    bodyStyles: { textColor: [17, 24, 39] },
  });

  return doc;
};